<?php

namespace App\Repositories;

use App\Models\Hero;
use App\Repositories\BaseRepository;

class HeroEloquentRepository extends BaseRepository
{
    /**
     * Specify Model class name.
     *
     * @return mixed
     */
    public function model()
    {
        return Hero::class;
    }

    public function getListHero()
    {
        return $this->model->orderBy('name')->get()->toArray(); // TODO: Change the autogenerated stub
    }
}
